import { Plus_Jakarta_Sans } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/miniCalendar.css";
import "@/styles/fullCalendar.css";
import ReduxProvider from "@/redux/reduxProvider";
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal"],
});

export const metadata = {
  title: "Google Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
